### ISSUE TITLE
Multiple People Crafting Support [Feature Request]

### ISSUE THREAD

**Issue by TheErikkuBlade** [Cerapter/pf2e-heroic-crafting-automation#1]
At the current moment, this part of Heroic Crafting doesn't seem to be supported. I'm not sure how exactly it would be implemented, but simply allowing the ability to manually add value to the project without requiring a check would be a very nice soft fix!

I understand that this would likely be difficult to automate exactly, but thought it important to mention

**Comment by Cerapter** [comment]
I've originally wanted to add an edit menu for projects, which should handle the manual progress addition, but I forgor 💀

But I might be able to do multiple people crafting too. I have an idea how I'd do that.

**Comment by TheErikkuBlade** [comment]
Cool, looking forward to it! Keep up the good work!
