### ISSUE TITLE
Feature Request - Craft Formula for an Item

### ISSUE THREAD

**Issue by Unoblueboy** [Cerapter/pf2e-heroic-crafting-automation#12]
As part of the inventor as well as part of reverse engineering, there is an ability to craft formulas.

Is there a way to add a button on the crafting tab to allow a character to begin a project to craft a formula, as well as being able to Craft a Project to complete it?

**Comment by Cerapter** [comment]
This can be done already by creating items to represent formulas, and using the Begin/Craft a Project options on them.
